mat 1398 (gov module - Unit & simulation test cases)
maticnetwork/heimdall pull request #402
Opened 2020-08-20 09:37 UTC by temaniarpit27

2020-09-09 07:44 UTC, mankenavenkatesh requested changes

2020-09-09 07:44 UTC, mankenavenkatesh commented on gov/tally.go
> +		fmt.Println("here")
remove log

2020-09-09 07:44 UTC, mankenavenkatesh commented on gov/vote_test.go
> +func (suite *TallyTestSuite) TestGetVotesAllFunctions() {
```suggestion
func (suite *TallyTestSuite) TestGetAllVotesAll() {
```

2020-09-10 06:06 UTC, temaniarpit27 commented
@mankenavenkatesh : changes done, please review

2020-09-14 05:29 UTC, mankenavenkatesh approved these changes

2020-09-14 05:37 UTC, merged