clerk side handler
maticnetwork/heimdall pull request #487
Opened 2020-12-28 19:01 UTC by temaniarpit27

2020-12-29 07:24 UTC, ssandeep approved these changes

2020-12-29 07:27 UTC, ssandeep commented
Can you also `make lint` and fix them?

2020-12-29 15:01 UTC, anilCSE requested changes

2020-12-29 15:01 UTC, anilCSE commented on x/clerk/side_handler.go
> +func SideHandleMsgEventRecord(ctx sdk.Context, k keeper.Keeper, msg types.MsgEventRecordRequest, contractCaller helper.IContractCaller) (result abci.ResponseDeliverSideTx) {
split this line

2020-12-29 15:01 UTC, anilCSE commented on x/clerk/side_handler.go
> +		k.Logger(ctx).Error("BlockNumber in message doesn't match blocknumber in receipt", "MsgBlockNumber", msg.BlockNumber, "ReceiptBlockNumber", receipt.BlockNumber.Uint64())
split this line

2020-12-29 15:01 UTC, anilCSE commented on x/clerk/side_handler.go
> +func PostHandleMsgEventRecord(ctx sdk.Context, k keeper.Keeper, msg types.MsgEventRecordRequest, sideTxResult tmprototypes.SideTxResultType) (*sdk.Result, error) {
split this line

2020-12-29 15:01 UTC, anilCSE commented on x/clerk/types/msg.go
> +	txHash []byte,
We shouldn't change this. Let's use `HeimdallHash`

2020-12-30 10:41 UTC, temaniarpit27 commented on x/clerk/side_handler.go
> +				Code: uint32(6), // TODO should be changed like `sdk.CodeUnknownRequest`
we will address it later

2020-12-30 16:54 UTC, anilCSE approved these changes
lgtm, just small nit

2020-12-30 16:54 UTC, anilCSE commented on x/clerk/types/msg.go
> +	if len(msg.TxHash) == 0 {
Can't we use .Empty here?

2020-12-30 17:09 UTC, merged