Migrating Bor Module
maticnetwork/heimdall pull request #549
Opened 2021-02-11 10:33 UTC by saikumar0x1967

#543

2021-02-12 12:18 UTC, ssandeep requested changes

2021-02-12 12:18 UTC, ssandeep commented on x/bor/keeper/keeper.go
> +	//codespace sdk.CodespaceType
let's remove this

2021-02-12 12:18 UTC, ssandeep commented on x/bor/keeper/keeper.go
> +		if err := k.cdc.UnmarshalBinaryBare(iterator.Value(), &span); err == nil {
should we return an error if `err != nil`

2021-02-12 12:18 UTC, ssandeep commented on x/bor/keeper/keeper.go
> +			return
return err?

2021-02-12 12:18 UTC, ssandeep commented on x/bor/side_handler.go
> +				Code: uint32(6), // TODO should be changed like `sdk.CodeUnknownRequest `
Use `Code: sdkerrors.ErrUnknownRequest.ABCICode(),` instead.
Can you also change this in staking, clerk and checkpoint?

2021-02-12 12:19 UTC, ssandeep commented on x/bor/keeper/keeper.go
> +		if err := k.cdc.UnmarshalBinaryBare(iterator.Value(), &span); err == nil {
in the else clause, I mean.

2021-02-12 12:58 UTC, saikumar0x1967 commented
@ssandeep  review changes are done, please check once

2021-02-12 13:38 UTC, ssandeep approved these changes

2021-02-12 13:43 UTC, ssandeep commented on x/bor/keeper/keeper.go
> +			return
we need to return err here right @saikumar0x1967

2021-02-12 13:43 UTC, ssandeep commented on x/bor/side_handler.go
> +				Code: uint32(6), // TODO should be changed like `sdk.CodeUnknownRequest `
ok, other modules we'll take it up later.

2021-02-12 13:44 UTC, ssandeep approved these changes

2021-02-15 06:46 UTC, ssandeep approved these changes

2021-02-15 06:46 UTC, merged