Vaibhav/pos 284
maticnetwork/heimdall pull request #865
Opened 2022-08-02 13:58 UTC by VAIBHAVJINDAL3012

Added the CLI commands which were present in Rest but not in the CLI

2022-08-04 12:07 UTC, 0xsharma requested changes
Please add more comments to the code. There are places where double letter variable are being used. Please also convert them to meaningful variables.

Thank you.

2022-08-17 14:11 UTC, temaniarpit27 approved these changes

2022-08-18 05:47 UTC, 0xsharma approved these changes

2022-08-18 05:48 UTC, merged

2022-08-18 05:48 UTC, JekaMas approved these changes