Vaibhav/POS-608
maticnetwork/heimdall pull request #872
Opened 2022-08-25 11:52 UTC by VAIBHAVJINDAL3012

This PR includes the following major change-
1.Milestone Proposing in the bridge module.
2.Milestone Module.

2022-11-10 05:07 UTC, temaniarpit27 requested changes

2022-11-10 05:07 UTC, temaniarpit27 commented on milestone/handler.go
> +	if !bytes.Equal(msg.Proposer.Bytes(), validatorSet.Proposer.Signer.Bytes()) {
by the time msg reaches here, will propose and validatorSet.Proposer.Signer be always equal or can there be a case that they can be different?

2022-11-10 05:07 UTC, temaniarpit27 commented on milestone/keeper.go
> +	MilestoneKey = []byte{0x20} // Key to store milestone
check if these keys are not used anywhere else

2022-11-10 05:07 UTC, temaniarpit27 commented on milestone/keeper.go
> +	DefaultValue = []byte{0x01} // Value to store in CacheCheckpoint and CacheCheckpointACK & ValidatorSetChange Flag
fix comment

2022-11-10 05:07 UTC, temaniarpit27 commented on milestone/types/genesis.go
> +type GenesisState struct {
check for this once with other modules

2022-11-10 05:07 UTC, temaniarpit27 commented on milestone/types/merkel.go
> +package types
file name spelling

2022-11-14 08:11 UTC, VAIBHAVJINDAL3012 commented on bridge/setu/processor/milestone.go
> +		result, err := util.GetMilestoneCount(mp.cliCtx)
But if latestMilestone doesn't give the result because of some other errors then in that case we can't assume the count to be 0.

2022-11-29 12:41 UTC, closed without merging